/** The reference names describe what is actually drawn in the left viewport. */
const comparisons = {
  noise: {
    "curl-noise": "直線状の上昇",
    perlin: "格子ごとの乱数",
    "simplex-noise": "格子ごとの乱数",
    "value-noise": "補間しない乱数",
    worley: "一様な表面",
    "fractal-brownian-motion": "単一の周波数",
    "turbulence-noise": "折り返しのないノイズ",
    "ridged-multifractal-noise": "丸い起伏",
    "domain-warping": "座標を歪めない模様",
    periodic: "端がつながらない模様",
  },
  curves: {
    "cubic-hermite-curve": "始点と終点を直線で結ぶ",
    "be-zier-curve": "直線移動",
    "catmull-rom-spline": "通過点を折れ線で結ぶ",
    "b-spline": "制御点を折れ線で結ぶ",
    "non-uniform-rational-b-spline": "円弧の弦を進む",
    "arc-length-parameterization": "パラメータを等間隔に進める",
    lerp: "値を一瞬で切り替える",
    smoothstep: "一定の速さで変化する",
    easing: "等速で移動する",
    slerp: "角度の数値をそのまま混ぜる",
  },
  motion: {
    "exponential-damping": "位置を即座に合わせる",
    "spring-damper": "減衰せずに揺れ続ける",
    "critical-damping": "振動しながら戻る",
    pd: "角度の誤差だけで旋回する",
    seek: "到着時も減速しない",
    pursuit: "現在位置へ向かう",
    "wander-steering": "進行方向を突然変える",
    boids: "個別に飛ぶ",
    "flow-field-following": "一直線に流れる",
    "obstacle-avoidance-steering": "障害物を考慮しない",
  },
  particles: {
    billboard: "向きを固定した板",
    "stretched-billboard": "点状の火花",
    ribbon: "軌跡を残さない剣",
    flipbook: "最初のコマを表示する",
    "mesh-particles": "回転しない平面の破片",
    "soft-particles": "地面で急に切れる煙",
    size: "大きさと透明度が一定",
    "sub-emitters": "衝突して消えるだけ",
    surface: "中心一点から放出する",
    "velocity-alignment": "向きを固定する",
  },
  materials: {
    "uv-scrolling": "模様を固定する",
    "polar-coordinates": "角度を固定する",
    triplanar: "一方向から投影する",
    "flow-map": "一方向に模様を流す",
    "parallax-mapping": "平らな表面",
    "vertex-displacement": "固定した頂点",
    dissolve: "透明度だけで消す",
    "screen-space-distortion": "歪みのない背景",
    "texture-bombing": "規則正しい繰り返し",
    "channel-packing": "マスクを個別に読む",
  },
  fields: {
    "signed-distance-field": "固定した輪郭",
    "sphere-tracing": "小さい一定歩幅で進む",
    "constructive-solid-geometry": "形を重ねるだけ",
    "smooth-union": "硬い境界で合成する",
    metaballs: "独立した液滴",
    "domain-repetition": "一つの形状",
    "domain-deformation": "変形しない柱",
    "sdf-gradient": "法線による陰影なし",
    "jump-flooding-algorithm": "種点だけを表示する",
    "multi-channel-signed-distance-field": "低解像度の文字画像",
  },
  mesh: {
    "marching-cubes": "値の場を点で見る",
    "marching-squares": "値の場を格子で見る",
    "delaunay-triangulation": "点群だけを表示する",
    "voronoi-fracture": "割れないガラス",
    sweep: "中心線だけを表示する",
    "laplacian-smoothing": "凹凸のある輪郭",
    "subdivision-surface": "粗い制御メッシュ",
    "mesh-decimation": "細かい分割を維持する",
    "as-rigid-as-possible-deformation": "曲げた部分が縮む",
    "dual-quaternion-skinning": "線形ブレンドでくびれる",
  },
  lighting: {
    "physically-based-rendering": "単色の球",
    ggx: "狭いハイライト",
    fresnel: "角度に依存しない反射",
    "normal-mapping": "滑らかな面の法線",
    "anisotropic-reflection": "丸いハイライト",
    "subsurface-scattering": "表面で遮られる光",
    "image-based-lighting": "一つの光源",
    "clear-coat": "下地だけの光沢",
    toon: "連続する陰影",
    "rim-lighting": "縁の照明なし",
  },
  volume: {
    "volume-ray-marching": "一枚の平らな雲",
    "beer-lambert-law": "霧の吸収なし",
    "henyey-greenstein-phase-function": "向きに依存しない散乱",
    "rayleigh-scattering": "一定の空の色",
    "mie-scattering": "太陽の周囲に霞なし",
    "volumetric-fog": "空気中に光が見えない",
    "aerial-perspective": "遠くも同じコントラスト",
    "god-rays": "木漏れ日の光の筋なし",
    "weighted-blended-order-independent-transparency": "描画順で変わる重なり",
    "premultiplied-alpha": "黒い縁が混ざる補間",
  },
  post: {
    bloom: "発光部の周りににじみなし",
    "color-grading": "元の色調",
    "tone-mapping": "明部を白に切り詰める",
    "depth-of-field": "すべての距離にピントが合う",
    "motion-blur": "一瞬の位置だけ描く",
    "chromatic-aberration": "色チャンネルが重なる",
    depth: "輪郭線なし",
    ssao: "接地部分の陰影なし",
    "screen-space-reflections": "反射のない床",
    "temporal-anti-aliasing": "一回のサンプルで描く",
  },
  nature: {
    "gerstner-waves": "上下だけの波",
    "fft-ocean": "一つの規則的な波",
    "shallow-water-equations": "障害物を通り抜ける波",
    "height-field-wave-simulation": "波紋のない水面",
    caustics: "均一な水底の明るさ",
    whitewater: "泡のない波",
    buoyancy: "水位に追従しない箱",
    "hydraulic-erosion": "水による侵食なし",
    "thermal-erosion": "急な斜面を維持する",
    "procedural-wind-animation": "静止した木",
  },
  physics: {
    "semi-implicit-euler": "重力のない等速移動",
    "verlet-integration": "固定された紐",
    "runge-kutta": "大きい時間刻みのオイラー法",
    "fixed-timestep": "描画ごとに同じ距離だけ進む",
    "position-based-dynamics": "距離制約のない布",
    "extended-pbd": "硬い距離制約",
    "mass-spring-system": "弾性のない布",
    "shape-matching": "つぶれたままの塊",
    joints: "関節のない部品",
    friction: "摩擦のない床",
  },
  fluids: {
    "stable-fluids": "上昇だけの煙",
    "semi-lagrangian-advection": "静止した染料",
    "pressure-projection": "外向きに広がる速度場",
    "vorticity-confinement": "弱まる渦",
    "smoothed-particle-hydrodynamics": "独立した粒子",
    "position-based-fluids": "粒子が重なる液体",
    "particle-in-cell": "粒子の位置だけ表示する",
    "affine-particle-in-cell": "回転が弱まる粒子群",
    "material-point-method": "ばらばらになる粒",
    "reaction-diffusion": "初期の斑点",
  },
  animation: {
    "two-bone": "固定した脚の姿勢",
    "full-body-ik": "腕だけを伸ばす",
    "forward-and-backward-reaching-ik": "固定した触手",
    "foot-ik": "足を地形に合わせない",
    "root-motion": "足運びと移動速度が不一致",
    "motion-warping": "決まった距離だけ踏み込む",
    "motion-matching": "同じ動きを繰り返す",
    inertialization: "姿勢が突然切り替わる",
    "additive-animation": "呼吸のない待機姿勢",
    "vertex-animation-textures": "静止したメッシュ",
  },
  generation: {
    "wave-function-collapse": "接続を考慮しないタイル",
    "l-system": "一本の幹",
    "space-colonization-algorithm": "分岐しない幹",
    "cellular-automata": "ランダムな地形セル",
    "binary-space-partitioning": "区切りのない空間",
    "wang-tiles": "辺の接続が合わないタイル",
    "island-falloff": "端まで続く地形",
    "biome-map": "一種類の地形",
    "point-relaxation": "密集のある配置",
    "density-masked-scattering": "一様な密度の草",
  },
  sampling: {
    "poisson-disk-sampling": "独立したランダム配置",
    "blue-noise": "密集のある試料点",
    stratified: "区画を考慮しない試料点",
    "low-discrepancy-sequence": "独立したランダム配置",
    "uniform-sphere-sampling": "緯度を一様に選ぶ",
    "uniform-disk": "半径を一様に選ぶ",
    "cosine-weighted-hemisphere-sampling": "角度を一様に選ぶ",
    "importance-sampling": "全方向を一様に選ぶ",
    "alias-method": "種類を同じ確率で選ぶ",
    gaussian: "四角形内の一様なばらつき",
  },
  navigation: {
    "a-search": "壁を考慮しない移動",
    "dijkstra-s-algorithm": "移動コストを考慮しない範囲",
    "navigation-mesh": "歩行可能領域を無視する",
    "funnel-algorithm": "領域の中心を順に通る",
    "optimal-reciprocal-collision-avoidance": "互いに直進する群集",
    "behavior-tree": "状況によらず巡回する",
    "finite-state-machine": "一つの状態を続ける",
    "goal-oriented-action-planning": "目標なしに移動する",
    "blackboard-architecture": "敵が情報を共有しない",
    "environment-query": "遮蔽物を考慮しない位置選び",
  },
  collision: {
    "ray-casting": "障害物を通過する照準",
    "continuous-collision-detection": "フレーム時点の位置だけ判定",
    "axis-aligned-bounding-box": "形状だけを表示する",
    "separating-axis-theorem": "回転を無視した外接箱",
    "gilbert-johnson-keerthi-algorithm": "外接円による粗い候補",
    "bounding-volume-hierarchy": "すべての物体を候補にする",
    "spatial-hashing": "すべての粒子を候補にする",
    "sweep-and-prune": "すべての区間を比較する",
    "morton-code": "登録順で並べる",
    "broad-phase": "すべての組を候補にする",
  },
  camera: {
    "camera-dead-zone": "小さな動きにも追従する",
    "camera-lookahead": "常にキャラを中央に置く",
    "impulse-camera-shake": "揺れのない着地",
    "coyote-time": "崖を離れたらジャンプ不可",
    input: "着地前の入力を捨てる",
    "corner-correction": "角で頭が止まる",
    "jump-apex-hang-time": "一定の重力",
    "camera-confiner": "ステージ外まで映る",
    "spline-dolly": "カメラが直線で移動する",
    "parallax-scrolling": "背景が同じ速さで動く",
  },
  performance: {
    "compute-shader": "一列で順番に更新するモデル",
    "gpu-instancing": "個別に描画要求を出すモデル",
    "indirect-drawing": "CPUで個数を渡すモデル",
    "level-of-detail": "遠景も細かい形状",
    frustum: "視野外も描画の候補にする",
    overdraw: "重なりを通常表示する",
    "ping-pong-buffers": "同じバッファを読み書きする",
    "object-pool": "毎回生成・破棄するモデル",
    "structure-of-arrays": "個体ごとにデータを並べる",
    "parallel-prefix-sum": "生存フラグだけを表示する",
  },
  dotnet: {
    "plain-old-clr-object": "表示と位置データが一体",
  },
} as const;

export type DemoFamily = keyof typeof comparisons;
export type DemoPreset = { family: DemoFamily; reference: string };

const isDemoFamily = (value: string): value is DemoFamily =>
  Object.hasOwn(comparisons, value);

export const demoPresets: ReadonlyMap<string, DemoPreset> = new Map(
  Object.entries(comparisons).flatMap(([family, entries]) => {
    if (!isDemoFamily(family)) {
      return [];
    }
    return Object.entries(entries).map(
      ([slug, reference]) => [slug, { family, reference }] as const
    );
  })
);

export const illustrativeFamilies = new Set<DemoFamily>([
  "mesh",
  "lighting",
  "volume",
  "fluids",
  "animation",
  "navigation",
  "collision",
  "performance",
  "dotnet",
  "physics",
  "generation",
  "nature",
]);

export const illustrativeSlugs = new Set([
  "multi-channel-signed-distance-field",
  "jump-flooding-algorithm",
  "triplanar",
  "channel-packing",
  "alias-method",
  "temporal-anti-aliasing",
  "screen-space-reflections",
]);

export const DEMO_DURATION = 8;
